In [1]:
#import sklearn 
#from sklearn.cross_validation import train_test_split
#from sklearn.[family] import [Model]
#from sklearn.linear_model import LinearRegression

import pandas as pd
import numpy as np
import os
#!pip install sklearn.family

#!pip install sklearn

#os chidir('c\\user\\hp\\Destop\\Edureka hindi\\Skelearn')
os.getcwd()
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)
pd.set_option('display.width',None)

In [2]:
data = pd.read_csv(r'C:\Users\Ashutosh\iris.csv')

In [3]:
data

sepal.length  sepal.width  petal.length  petal.width     variety
0             5.1          3.5           1.4          0.2      Setosa
1             4.9          3.0           1.4          0.2      Setosa
2             4.7          3.2           1.3          0.2      Setosa
3             4.6          3.1           1.5          0.2      Setosa
4             5.0          3.6           1.4          0.2      Setosa
5             5.4          3.9           1.7          0.4      Setosa
6             4.6          3.4           1.4          0.3      Setosa
7             5.0          3.4           1.5          0.2      Setosa
8             4.4          2.9           1.4          0.2      Setosa
9             4.9          3.1           1.5          0.1      Setosa
10            5.4          3.7           1.5          0.2      Setosa
11            4.8          3.4           1.6          0.2      Setosa
12            4.8          3.0           1.4          0.1      Setosa
13            4.3          3.0           1.1          0.1      Setosa
14            5.8          4.0           1.2          0.2      Setosa
15            5.7          4.4           1.5          0.4      Setosa
16            5.4          3.9           1.3          0.4      Setosa
17            5.1          3.5           1.4          0.3      Setosa
18            5.7          3.8           1.7          0.3      Setosa
19            5.1          3.8           1.5          0.3      Setosa
20            5.4          3.4           1.7          0.2      Setosa
21            5.1          3.7           1.5          0.4      Setosa
22            4.6          3.6           1.0          0.2      Setosa
23            5.1          3.3           1.7          0.5      Setosa
24            4.8          3.4           1.9          0.2      Setosa
25            5.0          3.0           1.6          0.2      Setosa
26            5.0          3.4           1.6          0.4      Setosa
27            5.2          3.5           1.5          0.2      Setosa
28            5.2          3.4           1.4          0.2      Setosa
29            4.7          3.2           1.6          0.2      Setosa
30            4.8          3.1           1.6          0.2      Setosa
31            5.4          3.4           1.5          0.4      Setosa
32            5.2          4.1           1.5          0.1      Setosa
33            5.5          4.2           1.4          0.2      Setosa
34            4.9          3.1           1.5          0.2      Setosa
35            5.0          3.2           1.2          0.2      Setosa
36            5.5          3.5           1.3          0.2      Setosa
37            4.9          3.6           1.4          0.1      Setosa
38            4.4          3.0           1.3          0.2      Setosa
39            5.1          3.4           1.5          0.2      Setosa
40            5.0          3.5           1.3          0.3      Setosa
41            4.5          2.3           1.3          0.3      Setosa
42            4.4          3.2           1.3          0.2      Setosa
43            5.0          3.5           1.6          0.6      Setosa
44            5.1          3.8           1.9          0.4      Setosa
45            4.8          3.0           1.4          0.3      Setosa
46            5.1          3.8           1.6          0.2      Setosa
47            4.6          3.2           1.4          0.2      Setosa
48            5.3          3.7           1.5          0.2      Setosa
49            5.0          3.3           1.4          0.2      Setosa
50            7.0          3.2           4.7          1.4  Versicolor
51            6.4          3.2           4.5          1.5  Versicolor
52            6.9          3.1           4.9          1.5  Versicolor
53            5.5          2.3           4.0          1.3  Versicolor
54            6.5          2.8           4.6          1.5  Versicolor
55            5.7          2.8           4.5          1.3  Versicolor
56            6

In [4]:
data.iloc[:,0:5]

sepal.length  sepal.width  petal.length  petal.width     variety
0             5.1          3.5           1.4          0.2      Setosa
1             4.9          3.0           1.4          0.2      Setosa
2             4.7          3.2           1.3          0.2      Setosa
3             4.6          3.1           1.5          0.2      Setosa
4             5.0          3.6           1.4          0.2      Setosa
5             5.4          3.9           1.7          0.4      Setosa
6             4.6          3.4           1.4          0.3      Setosa
7             5.0          3.4           1.5          0.2      Setosa
8             4.4          2.9           1.4          0.2      Setosa
9             4.9          3.1           1.5          0.1      Setosa
10            5.4          3.7           1.5          0.2      Setosa
11            4.8          3.4           1.6          0.2      Setosa
12            4.8          3.0           1.4          0.1      Setosa
13            4.3          3.0           1.1          0.1      Setosa
14            5.8          4.0           1.2          0.2      Setosa
15            5.7          4.4           1.5          0.4      Setosa
16            5.4          3.9           1.3          0.4      Setosa
17            5.1          3.5           1.4          0.3      Setosa
18            5.7          3.8           1.7          0.3      Setosa
19            5.1          3.8           1.5          0.3      Setosa
20            5.4          3.4           1.7          0.2      Setosa
21            5.1          3.7           1.5          0.4      Setosa
22            4.6          3.6           1.0          0.2      Setosa
23            5.1          3.3           1.7          0.5      Setosa
24            4.8          3.4           1.9          0.2      Setosa
25            5.0          3.0           1.6          0.2      Setosa
26            5.0          3.4           1.6          0.4      Setosa
27            5.2          3.5           1.5          0.2      Setosa
28            5.2          3.4           1.4          0.2      Setosa
29            4.7          3.2           1.6          0.2      Setosa
30            4.8          3.1           1.6          0.2      Setosa
31            5.4          3.4           1.5          0.4      Setosa
32            5.2          4.1           1.5          0.1      Setosa
33            5.5          4.2           1.4          0.2      Setosa
34            4.9          3.1           1.5          0.2      Setosa
35            5.0          3.2           1.2          0.2      Setosa
36            5.5          3.5           1.3          0.2      Setosa
37            4.9          3.6           1.4          0.1      Setosa
38            4.4          3.0           1.3          0.2      Setosa
39            5.1          3.4           1.5          0.2      Setosa
40            5.0          3.5           1.3          0.3      Setosa
41            4.5          2.3           1.3          0.3      Setosa
42            4.4          3.2           1.3          0.2      Setosa
43            5.0          3.5           1.6          0.6      Setosa
44            5.1          3.8           1.9          0.4      Setosa
45            4.8          3.0           1.4          0.3      Setosa
46            5.1          3.8           1.6          0.2      Setosa
47            4.6          3.2           1.4          0.2      Setosa
48            5.3          3.7           1.5          0.2      Setosa
49            5.0          3.3           1.4          0.2      Setosa
50            7.0          3.2           4.7          1.4  Versicolor
51            6.4          3.2           4.5          1.5  Versicolor
52            6.9          3.1           4.9          1.5  Versicolor
53            5.5          2.3           4.0          1.3  Versicolor
54            6.5          2.8           4.6          1.5  Versicolor
55            5.7          2.8           4.5          1.3  Versicolor
56            6

In [5]:
x=data.iloc[:,0:4].values

In [6]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [7]:
y=data['variety'].values

In [8]:
y

array(['Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolo

In [9]:
from sklearn.preprocessing import LabelEncoder

In [10]:
labelencoder_y=LabelEncoder()

In [11]:
y = labelencoder_y.fit_transform(y)

In [12]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [15]:
from sklearn.linear_model import LogisticRegression

In [16]:
logmodel = LogisticRegression()

In [17]:
logmodel.fit(x_train,y_train)

LogisticRegression()

In [18]:
y_pred = logmodel.predict(x_test)

In [19]:
y_pred

array([2, 2, 1, 1, 2, 1, 0, 1, 1, 1, 1, 2, 0, 1, 1, 0, 2, 2, 0, 1, 0, 2,
       1, 0, 2, 0, 1, 1, 1, 2])

In [20]:
y_test

array([2, 2, 1, 1, 2, 1, 0, 2, 2, 1, 1, 2, 0, 1, 1, 0, 2, 2, 0, 1, 0, 2,
       1, 0, 2, 0, 1, 1, 1, 2])

In [21]:
from sklearn.metrics import confusion_matrix

In [22]:
confusion_matrix(y_test,y_pred)

array([[ 7,  0,  0],
       [ 0, 12,  0],
       [ 0,  2,  9]], dtype=int64)

In [23]:
29/30

0.9666666666666667

In [24]:
  from sklearn.neighbors import KNeighborsClassifier

In [25]:
classifirer_knn = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)

In [26]:
classifirer_knn.fit(x_train,y_train)

KNeighborsClassifier()

In [27]:
y_pred=classifirer_knn.predict(x_test)

In [28]:
y_pred

array([2, 2, 1, 1, 2, 1, 0, 1, 2, 1, 1, 2, 0, 1, 1, 0, 2, 2, 0, 1, 0, 2,
       1, 0, 2, 0, 1, 1, 1, 2])

In [29]:
y_test

array([2, 2, 1, 1, 2, 1, 0, 2, 2, 1, 1, 2, 0, 1, 1, 0, 2, 2, 0, 1, 0, 2,
       1, 0, 2, 0, 1, 1, 1, 2])

In [30]:
confusion_matrix(y_test,y_pred)

array([[ 7,  0,  0],
       [ 0, 12,  0],
       [ 0,  1, 10]], dtype=int64)

In [31]:
30/30

1.0

In [32]:
 from sklearn.naive_bayes import GaussianNB

In [33]:
classifire_nb = GaussianNB()

In [34]:
classifire_nb.fit(x_train,y_train)

GaussianNB()

In [35]:
y_pred=classifire_nb.predict(x_test)

In [36]:
confusion_matrix(y_test,y_pred)

array([[ 7,  0,  0],
       [ 0, 12,  0],
       [ 0,  1, 10]], dtype=int64)

In [37]:
29/30

0.9666666666666667

In [41]:
from sklearn.svm import SVC

In [42]:
classifier_svm_sigmoid = SVC(kernel='sigmoid')

In [43]:
classifier_svm_sigmoid.fit(x_train,y_train)

SVC(kernel='sigmoid')

In [44]:
y_pred=classifier_svm_sigmoid.predict(x_test)

In [46]:
confusion_matrix(y_test,y_pred)

array([[ 7,  0,  0],
       [12,  0,  0],
       [11,  0,  0]], dtype=int64)

In [47]:
7/30

0.23333333333333334

In [49]:
from sklearn.svm import SVC

In [50]:
classifier_svm_linear = SVC(kernel='linear')

In [51]:
classifier_svm_linear.fit(x_train,y_train)

SVC(kernel='linear')

In [52]:
y_pred = classifier_svm_linear.predict(x_test)

In [53]:
confusion_matrix(y_test,y_pred)

array([[ 7,  0,  0],
       [ 0, 12,  0],
       [ 0,  1, 10]], dtype=int64)

In [54]:
29/30

0.9666666666666667

In [55]:
from sklearn.svm import SVC

In [62]:
classifier_svm_rbf = SVC(kernel='rbf')

In [63]:
classifier_svm_rbf.fit(x_train,y_train)

SVC()

In [64]:
y_pred =classifier_svm_rbf.predict(x_test)

In [65]:
confusion_matrix(y_test,y_pred)

array([[ 7,  0,  0],
       [ 0, 12,  0],
       [ 0,  1, 10]], dtype=int64)

In [66]:
29/30

0.9666666666666667

In [67]:
from sklearn.svm import SVC

In [68]:
classifier_svm_poly = SVC(kernel='poly')

In [69]:
classifier_svm_poly.fit(x_train,y_train)

SVC(kernel='poly')

In [72]:
y_pred =classifier_svm_poly.predict(x_test)

In [73]:
confusion_matrix(y_test,y_pred)

array([[ 7,  0,  0],
       [ 0, 12,  0],
       [ 0,  1, 10]], dtype=int64)

In [74]:
29/30

0.9666666666666667

In [75]:
from sklearn.tree import DecisionTreeClassifier

In [78]:
classifier_dt = DecisionTreeClassifier(criterion='entropy')

In [79]:
classifier_dt.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy')

In [80]:
y_pred  = classifier_dt.predict(x_test)

In [82]:
confusion_matrix(y_test,y_pred)

array([[ 7,  0,  0],
       [ 0, 12,  0],
       [ 0,  0, 11]], dtype=int64)

In [83]:
30/30

1.0

In [84]:
from sklearn.ensemble import RandomForestClassifier

In [86]:
classifier_rf = RandomForestClassifier(n_estimators=3,criterion='entropy')

In [87]:
classifier_rf.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=3)

In [88]:
y_pred= classifier_rf.predict(x_test)

In [89]:
confusion_matrix(y_test,y_pred)

array([[ 7,  0,  0],
       [ 0, 12,  0],
       [ 0,  1, 10]], dtype=int64)

In [90]:
29/30

0.9666666666666667